# Generated by Django 5.0 on 2025-11-04 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_favorite"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Route Name")),
                (
                    "origin_lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Origin Latitude"
                    ),
                ),
                (
                    "origin_lng",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Origin Longitude"
                    ),
                ),
                (
                    "origin_name",
                    models.CharField(
                        default="My Location",
                        max_length=255,
                        verbose_name="Origin Name",
                    ),
                ),
                (
                    "destination_lat",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="Destination Latitude",
                    ),
                ),
                (
                    "destination_lng",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        verbose_name="Destination Longitude",
                    ),
                ),
                (
                    "destination_name",
                    models.CharField(max_length=255, verbose_name="Destination Name"),
                ),
                (
                    "distance_text",
                    models.CharField(max_length=50, verbose_name="Distance"),
                ),
                (
                    "duration_text",
                    models.CharField(max_length=50, verbose_name="Duration"),
                ),
                (
                    "distance_value",
                    models.IntegerField(verbose_name="Distance in meters"),
                ),
                (
                    "duration_value",
                    models.IntegerField(verbose_name="Duration in seconds"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Used"
                    ),
                ),
                (
                    "destination_building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routes_to_here",
                        to="accounts.building",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Route",
                "verbose_name_plural": "Saved Routes",
                "ordering": ["-last_used", "-created_at"],
            },
        ),
    ]
