# Generated by Django 5.0 on 2025-11-05 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_savedroute"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Alert Title")),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("construction", "Construction"),
                            ("emergency", "Emergency"),
                            ("maintenance", "Maintenance"),
                            ("hazard", "Hazard"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Alert Type",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Severity",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("point", "Point"),
                            ("circle", "Circle"),
                            ("polygon", "Polygon"),
                        ],
                        default="point",
                        max_length=20,
                        verbose_name="Location Type",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Latitude"
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Longitude"
                    ),
                ),
                (
                    "radius",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Required for circle location type",
                        max_digits=10,
                        null=True,
                        verbose_name="Radius (meters)",
                    ),
                ),
                (
                    "polygon_coordinates",
                    models.TextField(
                        blank=True,
                        help_text="JSON array of [lat, lng] pairs: [[lat1, lng1], [lat2, lng2], ...]",
                        null=True,
                        verbose_name="Polygon Coordinates",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Date"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Safety Alert",
                "verbose_name_plural": "Safety Alerts",
                "ordering": ["-severity", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "severity"],
                        name="accounts_sa_is_acti_20a423_idx",
                    ),
                    models.Index(
                        fields=["alert_type", "is_active"],
                        name="accounts_sa_alert_t_0fa5f4_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="accounts_sa_created_f182d2_idx"
                    ),
                ],
            },
        ),
    ]
