# Generated by Django 5.0 on 2025-11-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_safetyalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="safetyalert",
            name="address",
            field=models.TextField(
                blank=True,
                help_text="Address for geocoding (optional if coordinates are provided)",
                null=True,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="safetyalert",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional - will be geocoded from address if not provided",
                max_digits=9,
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AlterField(
            model_name="safetyalert",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Optional - will be geocoded from address if not provided",
                max_digits=9,
                null=True,
                verbose_name="Longitude",
            ),
        ),
    ]
