# Generated by Django 5.0 on 2025-11-05 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_safetyalert_address_alter_safetyalert_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_address', models.TextField(help_text='Address or description of the location', verbose_name='Location Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Auto-filled from GPS if available', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Auto-filled from GPS if available', max_digits=9, null=True, verbose_name='Longitude')),
                ('category', models.CharField(choices=[('broken_light', 'Broken Light'), ('unsafe_path', 'Unsafe Path'), ('obstruction', 'Obstruction'), ('vandalism', 'Vandalism'), ('maintenance', 'Maintenance Issue'), ('other', 'Other')], max_length=50, verbose_name='Category')),
                ('description', models.TextField(help_text='Detailed description of the safety concern', verbose_name='Description')),
                ('photo', models.ImageField(blank=True, help_text='Optional photo of the safety concern', null=True, upload_to='safety_concerns/', verbose_name='Photo')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from campus security', null=True, verbose_name='Admin Notes')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_concerns', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
            ],
            options={
                'verbose_name': 'Safety Concern',
                'verbose_name_plural': 'Safety Concerns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='accounts_sa_status_b7b127_idx'), models.Index(fields=['category', 'status'], name='accounts_sa_categor_e9ade3_idx')],
            },
        ),
    ]
