# Generated by Django 5.0 on 2025-11-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_safetyconcern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safetyconcern',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
