# Generated by Django 5.2.7 on 2025-11-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_safetyconcern_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="safetyconcern",
            name="category",
            field=models.CharField(
                choices=[
                    ("construction", "Construction/Roadwork"),
                    ("emergency", "Emergency Situation"),
                    ("maintenance", "Maintenance Issue"),
                    ("hazard", "Safety Hazard"),
                    ("broken_light", "Broken Light"),
                    ("unsafe_path", "Unsafe Path"),
                    ("obstruction", "Obstruction"),
                    ("vandalism", "Vandalism"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="Category",
            ),
        ),
    ]
