# Generated by Django 5.0 on 2025-11-18 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_safetyconcern_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("view", "Viewed"),
                            ("click", "Clicked"),
                            ("details", "Viewed Details"),
                        ],
                        default="view",
                        max_length=20,
                        verbose_name="Interaction Type",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Session ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Interaction At"
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_logs",
                        to="accounts.safetyalert",
                        verbose_name="Safety Alert",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_interactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Interaction",
                "verbose_name_plural": "Alert Interactions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["alert", "timestamp"],
                        name="accounts_al_alert_i_dab380_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="accounts_al_user_id_cb7542_idx",
                    ),
                    models.Index(
                        fields=["interaction_type", "timestamp"],
                        name="accounts_al_interac_b36f63_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BuildingView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "view_type",
                    models.CharField(
                        choices=[
                            ("search", "Search"),
                            ("details", "Details View"),
                            ("directions", "Directions Request"),
                        ],
                        default="search",
                        max_length=20,
                        verbose_name="View Type",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Anonymous session tracking",
                        max_length=100,
                        verbose_name="Session ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Viewed At"),
                ),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_logs",
                        to="accounts.building",
                        verbose_name="Building",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="building_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Building View",
                "verbose_name_plural": "Building Views",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["building", "timestamp"],
                        name="accounts_bu_buildin_281b5b_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="accounts_bu_user_id_1f9fce_idx",
                    ),
                    models.Index(
                        fields=["view_type", "timestamp"],
                        name="accounts_bu_view_ty_5bf5f6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_path",
                    models.CharField(
                        help_text="URL path of the page viewed",
                        max_length=255,
                        verbose_name="Page Path",
                    ),
                ),
                (
                    "page_name",
                    models.CharField(
                        blank=True,
                        help_text="Friendly name for the page",
                        max_length=100,
                        verbose_name="Page Name",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Session ID"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Viewed At"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_views",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page View",
                "verbose_name_plural": "Page Views",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="accounts_pa_user_id_59b159_idx",
                    ),
                    models.Index(
                        fields=["page_path", "timestamp"],
                        name="accounts_pa_page_pa_b6a281_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="accounts_pa_timesta_22a0e1_idx"
                    ),
                ],
            },
        ),
    ]
