# Generated by Django 5.0 on 2025-11-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alertinteraction_buildingview_pageview"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="best_study_spot",
            field=models.CharField(
                blank=True,
                help_text="Recommended study area",
                max_length=255,
                verbose_name="Best Study Spot",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="current_occupancy_percent",
            field=models.IntegerField(
                blank=True,
                help_text="Current occupancy percentage (0-100)",
                null=True,
                verbose_name="Current Occupancy %",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="next_hour_prediction",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Next Hour Prediction"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="occupancy_last_updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Occupancy Last Updated"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="occupancy_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_busy", "Not Busy"),
                    ("moderate", "Moderate"),
                    ("busy", "Busy"),
                    ("very_busy", "Very Busy"),
                ],
                max_length=20,
                verbose_name="Occupancy Status",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="operating_hours",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Operating Hours"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="peak_hours",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of peak hours",
                max_length=255,
                verbose_name="Peak Hours",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="waitz_id",
            field=models.CharField(
                blank=True,
                help_text="Waitz.io building identifier",
                max_length=100,
                null=True,
                verbose_name="Waitz ID",
            ),
        ),
    ]
